version: "3.8"
services:
    risk-db:
        container_name: risk-db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'risk123'
            MYSQL_PASSWORD: 'risk123'
            MYSQL_DATABASE: 'risk'
        ports:
            - 8765:3306

    board-api:
        container_name: board-api-risk
        image: board-api
        environment:
            DB_HOST: 'risk-db'
            DB_USER: 'risk123'
            DB_PASS: 'risk123'
            DB_NAME: 'risk'
            DB_PORT: '3306'
        ports:
            - 4321:8080

    player-api:
        container_name: player-api-risk
        image: player-api
        environment:
            DB_HOST: 'risk-db'
            DB_USER: 'risk123'
            DB_PASS: 'risk123'
            DB_NAME: 'risk'
            DB_PORT: '3306'
        ports:
            - 5432:8080

    combat-api:
        container_name: combat-api-risk
        image: combat-api
        ports:
            - 6543:8080
